version: '3.8'

services:
  # backend:
  #   image: ahamednazeer/ai-driven-classroom-engagement-analytics:be-01-amd
  #   container_name: classroom_backend
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - APP_NAME=AI-Driven Classroom Engagement
  #     - DEBUG=true
  #     - CORS_ORIGINS=http://localhost:3000
  #     - DATABASE_URL=postgresql+asyncpg://root:password@db:5432/classroom_engagement
  #     - SECRET_KEY=super-secret-key-change-in-production-abc123xyz
  #     - ALGORITHM=HS256
  #     - ACCESS_TOKEN_EXPIRE_MINUTES=480
  #     - ADMIN_USERNAME=admin
  #     - ADMIN_PASSWORD=admin123
  #     - ADMIN_EMAIL=admin@classroom.local
  #     - JITSI_DOMAIN=8x8.vc
  #     - JITSI_APP_ID=vpaas-magic-cookie-68b8aa6f9d0f4538953b86d65c058184
  #     - JITSI_KID=vpaas-magic-cookie-68b8aa6f9d0f4538953b86d65c058184/c4085e
  #     - JITSI_ROOM_CLAIM=*
  #     - JITSI_ROOM_REGEX=false
  #   volumes:
  #     - ./backend/uploads:/app/uploads
  #   restart: always

  frontend:
    image: ahamednazeer/ai-driven-classroom-engagement-analytics:fe-01-amd
    container_name: classroom_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    restart: always

volumes:
  postgres_data:
